// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)

import PreviewController from "controllers/preview_controller"
application.register("preview", PreviewController)